CORRELATION_ID_WIDTH = 4
API_KEY_WIDTH = 2
PAYLOAD_LENGTH_WIDTH = 4
HEADER_WIDTH = CORRELATION_ID_WIDTH + API_KEY_WIDTH + PAYLOAD_LENGTH_WIDTH

LOG_FILENAME_LENGTH = 20
LOG_FILE_SIZE_LIMIT = 1024**3  # 1 GB
LOG_RECORD_OFFSET_WIDTH = 8
LOG_RECORD_POSITION_WIDTH = 8
